version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 12
  pre_build:	
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build
        - cp -p appspec.yml dist
        - zip -r scripts.zip scripts
        - cp -p scripts.zip dist
        - cd dist
        - unzip scripts.zip
        - rm scripts.zip
        - cd ../
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
