version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 12
  pre_build:	
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build
  post_build:
    commands:
      - mkdir staging
      - cp -avr dist staging
      - cp -avr scripts staging
      - cp -p appspec.yml staging             
artifacts:
    files:
        - '**/*'
    base-directory: staging
