version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 12
  pre_build:	
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build
        - cp -p appspec.yml dist
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
